import { Movie } from './types';

// High-fidelity fallback catalog with authentic TMDB IDs and artwork
export const MOVIES: Movie[] = [
  {
    id: '693134',
    title: 'Дюна: Частина друга',
    description: 'Пол Атрід об\'єднується з Чані та фременами, прагнучи помсти змовникам, які знищили його родину. Перед лицем вибору між коханням усього життя та долею відомого всесвіту він намагається запобігти жахливому майбутньому.',
    bannerUrl: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520049.jpg',
    posterUrl: 'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    smallPosterUrl: 'https://image.tmdb.org/t/p/w342/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    genre: ['Наукова фантастика', 'Пригоди'],
    genreIds: [878, 12],
    duration: '2h 46m',
    rating: '8.2',
    year: 2024,
    match: 96,
    mediaType: 'movie',
  },
  {
    id: '157336',
    title: 'Інтерстеллар',
    description: 'Коли посуха, пилові бурі та вимирання рослин призводять людство до продовольчої кризи, група дослідників використовує нещодавно виявлену просторово-часову діру, щоб знайти новий дім для людства.',
    bannerUrl: 'https://image.tmdb.org/t/p/original/rAiYTua5VoEg09vkmnVeFDGMs8k.jpg',
    posterUrl: 'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    smallPosterUrl: 'https://image.tmdb.org/t/p/w342/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    genre: ['Наукова фантастика', 'Драма', 'Пригоди'],
    genreIds: [878, 18, 12],
    duration: '2h 49m',
    rating: '8.4',
    year: 2014,
    match: 98,
    mediaType: 'movie',
  },
  {
    id: '872585',
    title: 'Оппенгеймер',
    description: 'Історія життя американського фізика-теоретика Роберта Оппенгеймера, який під час Другої світової війни очолював Мангеттенський проєкт зі створення першої у світі ядерної зброї.',
    bannerUrl: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    posterUrl: 'https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    smallPosterUrl: 'https://image.tmdb.org/t/p/w342/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    genre: ['Драма', 'Історичний'],
    genreIds: [18, 36],
    duration: '3h 00m',
    rating: '8.1',
    year: 2023,
    match: 94,
    mediaType: 'movie',
  },
  {
    id: '66732',
    title: 'Дивні дива',
    description: 'У тихому містечку Гокінс зникає маленький хлопчик. Його друзі, родина та місцева поліція вирушають на пошуки відповідей, відкриваючи таємні урядові експерименти та портал у потойбічний світ.',
    bannerUrl: 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    posterUrl: 'https://image.tmdb.org/t/p/w780/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    smallPosterUrl: 'https://image.tmdb.org/t/p/w342/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    genre: ['Фантастика', 'Драма', 'Містика'],
    genreIds: [10765, 18, 9648],
    duration: '4 Сезони',
    rating: '8.6',
    year: 2016,
    match: 97,
    mediaType: 'tv',
  },
  {
    id: '27205',
    title: 'Початок',
    description: 'Дом Кобб — талановитий злодій, найкращий у небезпечному мистецтві вилучення: він краде цінні секрети з глибин підсвідомості під час сну. Йому випадає шанс спокути через впровадження чужої ідеї.',
    bannerUrl: 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    posterUrl: 'https://image.tmdb.org/t/p/w780/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    smallPosterUrl: 'https://image.tmdb.org/t/p/w342/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    genre: ['Бойовик', 'Наукова фантастика', 'Пригоди'],
    genreIds: [28, 878, 12],
    duration: '2h 28m',
    rating: '8.4',
    year: 2010,
    match: 99,
    mediaType: 'movie',
  },
  {
    id: '569094',
    title: 'Людина-павук: Крізь всесвіт',
    description: 'Майлз Моралес катапультується через Мультивсесвіт, де зустрічає команду Людей-павуків, які захищають саме його існування. Коли герої сперечаються, як впоратися з новою загрозою, Майлз мусить перевизначити сенс геройства.',
    bannerUrl: 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    posterUrl: 'https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    smallPosterUrl: 'https://image.tmdb.org/t/p/w342/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    genre: ['Мультфільм', 'Бойовик', 'Пригоди'],
    genreIds: [16, 28, 12],
    duration: '2h 20m',
    rating: '8.4',
    year: 2023,
    match: 95,
    mediaType: 'movie',
  },
  {
    id: '94605',
    title: 'Аркейн',
    description: 'Серед гострого конфлікту між містами-близнюками Пілтовер та Заун дві сестри Вай і Джинкс борються по різні боки барикад у війні між магічними технологіями та несумісними переконаннями.',
    bannerUrl: 'https://image.tmdb.org/t/p/original/fqv8v6AycXKsivp1TddutaLIxio.jpg',
    posterUrl: 'https://image.tmdb.org/t/p/w780/abf8tYzULID59Aq2AvuvSdG0wwY.jpg',
    smallPosterUrl: 'https://image.tmdb.org/t/p/w342/abf8tYzULID59Aq2AvuvSdG0wwY.jpg',
    genre: ['Мультфільм', 'Наукова фантастика', 'Екшн'],
    genreIds: [16, 10765, 10759],
    duration: '2 Сезони',
    rating: '8.7',
    year: 2021,
    match: 98,
    mediaType: 'tv',
  },
  {
    id: '155',
    title: 'Темний лицар',
    description: 'Бетмен піднімає ставки у війні зі злочинністю. За допомогою лейтенанта Джима Ґордона та окружного прокурора Гарві Дента він має намір очистити вулиці Ґогема, але на шляху постає кримінальний геній Джокер.',
    bannerUrl: 'https://image.tmdb.org/t/p/original/oHzw2l3v2rB4b5vU0i2F6pA3b0X.jpg',
    posterUrl: 'https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    smallPosterUrl: 'https://image.tmdb.org/t/p/w342/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    genre: ['Драма', 'Бойовик', 'Кримінал'],
    genreIds: [18, 28, 80],
    duration: '2h 32m',
    rating: '8.5',
    year: 2008,
    match: 99,
    mediaType: 'movie',
  }
];

export const CATEGORIES = [
  { title: "Trending Now", filter: (m: Movie) => m.match > 90 },
  { title: "New Releases", filter: (m: Movie) => m.year >= 2022 },
  { title: "Sci-Fi & Fantasy", filter: (m: Movie) => m.genre.includes('Наукова фантастика') || m.genre.includes('Sci-Fi') },
  { title: "Action Thrillers", filter: (m: Movie) => m.genre.includes('Бойовик') || m.genre.includes('Action') },
];
